name: Build, Test, and Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: mvn --batch-mode clean test

      - name: Build app
        run: mvn --batch-mode clean package -DskipTests

      - name: Set JAR_FILE and FILE_NAME
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Found .jar file: $JAR_FILE"
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Remove previous app
        run: |
          PID=$(lsof -t -i:$APP_PORT || true)
          if [ -n "$PID" ]; then
            echo "Port $APP_PORT is busy"
            kill -9 $PID
          else
            echo "App port isn't busy"
          fi
        env:
          APP_PORT: ${{ vars.APP_PORT }}

      - name: Run app
        run: |
          java -jar "$JAR_FILE" &

      - name: Check app
        run: |
          echo "checUrl: $CHECK_URL"
          RESPONSE_STATUS=$(curl --write-out "%{http_code}" --silent --output /dev/null "$CHECK_URL")
          echo "response status: $RESPONSE_STATUS"
          if [ "$RESPONSE_STATUS" -eq 200 ]; then
            echo "successful with status = $RESPONSE_STATUS"
          else
            echo "error with status = $RESPONSE_STATUS"
            exit 1
          fi
        env:
          CHECK_URL: ${{ vars.CHECK_URL }}
