name: Test

on:
  push:
    branches:
      - main

env:
  BUILD_NAME: "hello-app"

jobs:
  run:
    name: Test simple-app image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
      pages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests && build
        run: mvn --batch-mode clean package -DskipTests

      - name: Build docker image
        run: docker build -t ${{ env.BUILD_NAME }} .

      - name: Run docker container
        run: |
          docker run --name  hello-app -d -p 8080:8080 ${{ env.BUILD_NAME }}
          sleep 30s

      - name: Test app
        run: |
          RESULT=`curl http://localhost:8080/api/hello`
          echo $RESULT
          if [ "$RESULT" == "Hello" ]
          then
            echo "SUCCESS"
          else
            echo "FAILURE"
            exit 1
          fi

      - name: Check user
        run: |
          RESULT=`docker exec hello-app whoami`
          echo $RESULT
          if [ "$RESULT" == "tester" ]
          then
            echo "SUCCESS"
          else
            echo "FAILURE"
            exit 1
          fi