name: Hello action
on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        run: sudo apt update && sudo apt install nodejs

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: node ./hello.js
